# -*- coding: utf-8 -*-
"""FULLMAP HARD GATE · JVM / JUC / Spring / Spark / Flink — deep rewrite"""
from ency_fullbar import gated_entry
from hardgate_bodies.chains import CHAINS


def jvm():
    return gated_entry(
        "ency-fm-jvm", "ENCY-FM · JVM全貌", "ENCY-FM-JVM",
        "JVM 全貌：内存·GC·诊断·容器·生产配置·金融/电商/物流",
        ["jvm", "gc", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>先分清堆/元空间/直接内存谁OOM；GC看P99；容器认cgroup limit；大促前压测不是上线后猜。",
        spine_pos="订单服务稳定性底座。", serves="RT/可用性", back="T-Found-JVM → FULLMAP",
        caps=[("内存布局","堆/元空间/直内存/栈","OOM分型"),("GC","G1/ZGC/停顿","P99"),("诊断","CPU/内存/线程","值班"),
              ("容器","cgroup与-Xmx","K8s"),("配置","HeapDump/GC日志","生产"),("场景","金融/电商/物流","选型")],
        mmds=[
            ("diag-fm-jvm-mem","flowchart TB\n  Proc-->Heap[堆新生代/老年代]\n  Proc-->Meta[元空间]\n  Proc-->Direct[直接内存]\n  Proc-->Stack[栈]\n"),
            ("diag-fm-jvm-diag","flowchart TD\n  Sym[CPU高/RT高/OOM]-->Tool{工具}\n  Tool-->JS[jstack]\n  Tool-->JM[jmap/dump]\n  Tool-->GC[GC日志]\n"),
        ],
        sources=[
            ("GC与分配","HotSpot GC / TLAB认知","对象优先 Eden；晋升老年代；GC日志看Pause与Allocation Rate\n"),
            ("容器内存","JVM识别container support","-XX:MaxRAMPercentage=... 或显式-Xmx < limit\n# 禁2G容器配4G堆\n"),
        ],
        floors=[("停顿与分配","GC停顿吃P99；泄漏表现为Old持续涨。","GC日志；NMT；MAT。","直内存OOM却怪堆。","GC pause、直内存、线程态。")],
        chain_html=CHAINS["jvm"],
        cases=[
            {"id":"ency-fm-jvm-case-pdd","company":"拼多多类大促（案例归纳）","scene":"下单RT毛刺",
             "land":"G1；堆固定；GC日志；压测同镜像。","pit":"容器limit与-Xmx不符致杀进程。",
             "fix":"①对齐limit ②看Pause ③大对象治理。",
             "effect":"公开分享量级/示意区间：P99毛刺收敛（示意）。"},
            {"id":"ency-fm-jvm-case-cmb","company":"招行类（案例归纳）","scene":"账务服务稳态",
             "land":"更严停顿目标；定期dump演练。","pit":"只看吞吐不看P99。",
             "fix":"①SLA含尾延迟 ②故障演练。",
             "effect":"公开分享量级/示意区间：以尾延迟达标为门禁（示意）。"},
            {"id":"ency-fm-jvm-case-sf","company":"顺丰类（案例归纳）","scene":"轨迹写入服务",
             "land":"直内存/Netty预算；堆外监控。","pit":"堆外泄漏进程被杀。",
             "fix":"①NMT/直内存指标 ②泄漏修复。",
             "effect":"公开分享量级/示意区间：非堆OOM显著下降（示意）。"},
            {"id":"ency-fm-jvm-case-mt","company":"美团/饿了么（案例归纳）","scene":"午高峰CPU",
             "land":"top -H+jstack对齐热点。","pit":"盲目加副本不解锁竞争。",
             "fix":"①定热点 ②减分配/锁 ③再扩容。",
             "effect":"公开分享量级/示意区间：高峰CPU回落（示意）。"},
        ],
        trade_title="GC取向",
        trade_rows=[("低停顿","ZGC/调G1","吞吐Parallel","按SLA"),("容器","MaxRAMPercentage","固定Xmx","对齐limit")],
        runbook_title="OOM/CPU飙/频繁GC",
        runbook_html="<ol><li>分清堆/元空间/直内存。</li><li>CPU：jstack对齐。</li><li>GC：看分配速率与泄漏。</li><li>容器：核对limit。</li></ol>",
        fail_html="<ul><li>Xmx&gt;limit。</li><li>无GC日志。</li><li>无HeapDumpOnOOM。</li></ul>",
        today_html="<ul><li>打开GC日志与OOM dump；容器内存对齐。</li></ul>",
        conf_title="生产基线",
        conf_code="-Xms=-Xmx；HeapDumpOnOutOfMemoryError\nGC日志落盘；直内存预算\n容器：MaxRAMPercentage或显式Xmx&lt;limit",
        qas=[
            ("【OOM】先分哪几类？",["堆/元空间/直内存/原生。","值班。","一律加堆。","对症工具。","「先分型再动手。」"],"fm-jvm-q1"),
            ("【GC】为啥盯P99？",["停顿直接吃尾延迟与超时。","大促。","只看吞吐。","GC日志+压测。","「尾延迟说话。」"],"fm-jvm-q2"),
            ("【容器】最常见坑？",["limit与堆不符被杀。","K8s。","宿主机内存很大就行。","对齐百分比。","「堆不得超过limit。」"],"fm-jvm-q3"),
        ],
        koujue_txt="JVM口诀：OOM先分型，GC看P99，容器对齐limit，日志dump常开。",
        rid="fm-jvm-r1",
    )


def juc():
    return gated_entry(
        "ency-fm-juc", "ENCY-FM · JUC全貌", "ENCY-FM-JUC",
        "JUC 全貌：JMM·AQS·线程池·CHM·订单并发·金融/电商/物流",
        ["juc", "aqs", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>JMM定可见有序；AQS是锁/信号量底板；线程池参数决定拒单还是堆积；跨机互斥别指望本地锁。",
        spine_pos="回调/履约并发与隔离。", serves="并发正确与隔离", back="T-Found-JUC → FULLMAP",
        caps=[("JMM","可见/有序/HB","状态标志"),("AQS","state+队列","锁底座"),("线程池","参数/拒绝策略","隔离"),
              ("CHM","桶级并发","缓存映射"),("订单并发","DB/Redis条件更新","库存"),("场景","金融/电商/物流","选型")],
        mmds=[
            ("diag-fm-juc-aqs","flowchart LR\n  Lock-->AQS[AQS state+CLH]\n  AQS-->Park[park/unpark]\n"),
            ("diag-fm-juc-pool","flowchart TD\n  Task-->Pool{线程池}\n  Pool -->|队列满| Rej[拒绝/调用者跑]\n  Pool -->|隔离| Biz[业务池 vs 回调池]\n"),
        ],
        sources=[
            ("AQS路径","AbstractQueuedSynchronizer#acquire/release","lock → tryAcquire → park\nunlock → release → unpark successor\n"),
            ("线程池执行","ThreadPoolExecutor#execute","if workers<core: addWorker\nelse if queue.offer: ok\nelse if workers<max: addWorker\nelse reject\n"),
        ],
        floors=[("HB与队列","无HB可能已写未见；池队列无界=隐形OOM。","AQS；TPE。","Executors.newFixed无界队列。","池活跃/队列长度/拒绝次数。")],
        chain_html=CHAINS["juc"],
        cases=[
            {"id":"ency-fm-juc-case-ali","company":"阿里系订单（案例归纳）","scene":"支付回调并发",
             "land":"回调池隔离；幂等；拒绝策略可观测。","pit":"与业务池共用打满互相饿死。",
             "fix":"①池隔离 ②监控拒绝 ③限流。",
             "effect":"公开分享量级/示意区间：回调堆积与业务RT解耦（示意）。"},
            {"id":"ency-fm-juc-case-pdd","company":"拼多多类秒杀（案例归纳）","scene":"本地锁误用",
             "land":"库存用DB/Redis原子；禁单机synchronized当集群锁。","pit":"本地锁以为全局限流。",
             "fix":"①分布式原子 ②对账。",
             "effect":"公开分享量级/示意区间：超卖工单下降（示意）。"},
            {"id":"ency-fm-juc-case-cmb","company":"招行类（案例归纳）","scene":"渠道回执并发",
             "land":"有界队列+CallerRuns/拒绝对账可观测。","pit":"静默丢任务。",
             "fix":"①拒绝打点 ②死信/重试表。",
             "effect":"公开分享量级/示意区间：任务可解释不丢（示意）。"},
            {"id":"ency-fm-juc-case-sf","company":"物流轨迹（案例归纳）","scene":"CPU自旋过多",
             "land":"减少热路径锁；批量写。","pit":"高竞争synchronized。",
             "fix":"①分段 ②无锁结构 ③扩分片。",
             "effect":"公开分享量级/示意区间：热点CPU下降（示意）。"},
        ],
        trade_title="并发手段边界",
        trade_rows=[("单机互斥","锁/AQS","跨机无效","—"),("跨机","DB条件更新/Redis","本地锁","—"),("隔离","独立线程池","共享池","—")],
        runbook_title="池打满/死锁/可见性BUG",
        runbook_html="<ol><li>看活跃线程/队列/拒绝。</li><li>jstack查死锁。</li><li>状态标志补同步。</li></ol>",
        fail_html="<ul><li>无界队列。</li><li>本地锁当集群锁。</li><li>吞拒绝。</li></ul>",
        today_html="<ul><li>业务/回调池隔离；拒绝打点；禁Executors默认无界。</li></ul>",
        conf_title="线程池基线意识",
        conf_code="core/max/queue/RejectHandler 显式\n回调池与业务池分离\n禁止 Executors.newFixedThreadPool 无界队列默认",
        qas=[
            ("【AQS】是什么？",["同步器底板：state+等待队列，锁/信号量复用。","原理。","只会用Lock。","画acquire。","「锁的操作系统。」"],"fm-juc-q1"),
            ("【池】队列满了？",["按拒绝策略：抛异常/调用者跑/丢弃；必须可观测。","高峰。","无限加大队列。","打点+隔离。","「拒绝要看得见。」"],"fm-juc-q2"),
            ("【订单】本地锁够吗？",["跨机不够；用DB/Redis原子+幂等。","秒杀。","加synchronized。","分布式原子。","「锁的范围要对齐部署。」"],"fm-juc-q3"),
        ],
        koujue_txt="JUC口诀：JMM讲可见，AQS做底板，线程池要隔离，跨机别用本地锁。",
        rid="fm-juc-r1",
    )


def spring():
    return gated_entry(
        "ency-fm-spring", "ENCY-FM · Spring全貌", "ENCY-FM-SPRING",
        "Spring 全貌：IoC·AOP事务·Boot·生产边界·金融/电商/物流",
        ["spring", "transaction", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>容器生命周期决定Bean如何来；事务靠代理，自调用会失效；短事务+Outbox，禁包HTTP。",
        spine_pos="订单服务应用框架。", serves="事务边界/装配", back="P0-Spring → FULLMAP",
        caps=[("IoC","生命周期/循环依赖","装配"),("AOP","代理/切面","横切"),("事务","传播/失效场景","支付"),
              ("Boot","自动配置/外部化","环境"),("生产","池/超时/端点","安全"),("场景","金融/电商/物流","选型")],
        mmds=[
            ("diag-fm-spring-ioc","flowchart TD\n  BD[BeanDefinition]-->Inst[实例化]-->Inj[注入]-->Init[初始化]-->Ready\n"),
            ("diag-fm-spring-tx","sequenceDiagram\n  participant C as Controller\n  participant S as Service代理\n  participant D as DB\n  C->>S: @Transactional\n  S->>D: 短事务\n  Note over S: 禁包HTTP\n"),
        ],
        sources=[
            ("刷新路径","AbstractApplicationContext#refresh","invokeBeanFactoryPostProcessors → finishBeanFactoryInitialization → getBean\n"),
            ("事务拦截","TransactionInterceptor / PlatformTransactionManager","getTransaction → invoke → commit/rollback\n# 自调用不经过代理 → 失效\n"),
        ],
        floors=[("代理边界","同类自调用绕过代理；异常被吞不回滚。","AOP代理；事务管理器。","长事务包远程。","事务耗时、回滚原因、连接占用。")],
        chain_html=CHAINS["spring"],
        cases=[
            {"id":"ency-fm-spring-case-ali","company":"阿里系订单（案例归纳）","scene":"支付本地事务+消息",
             "land":"短@Transactional；Outbox/事务消息；禁包渠道HTTP。","pit":"事务里调远程致连接打满。",
             "fix":"①拆事务 ②异步 ③超时。",
             "effect":"公开分享量级/示意区间：连接池耗尽事件下降（示意）。"},
            {"id":"ency-fm-spring-case-yy","company":"用友类（案例归纳）","scene":"多模块装配",
             "land":"明确配置外置；忌组件乱扫包。","pit":"错误自动配置覆盖。",
             "fix":"①配置审计 ②条件装配测试。",
             "effect":"公开分享量级/示意区间：环境一致性提升（示意）。"},
            {"id":"ency-fm-spring-case-cmb","company":"招行类（案例归纳）","scene":"事务失效致脏写",
             "land":"事务走代理；校验public；异常类型。","pit":"自调用@Transactional无效。",
             "fix":"①拆Bean ②IT用例。",
             "effect":"公开分享量级/示意区间：失效用例门禁化（示意）。"},
            {"id":"ency-fm-spring-case-mt","company":"美团/饿了么（案例归纳）","scene":"Actuator暴露面",
             "land":"端点鉴权；探针与业务分离策略。","pit":"heapdump等敏感端点裸奔。",
             "fix":"①收敛暴露 ②网关鉴权。",
             "effect":"公开分享量级/示意区间：攻击面收敛（示意）。"},
        ],
        trade_title="事务手段",
        trade_rows=[("本地短事务","默认","—","—"),("Outbox/消息","最终一致","长XA","—"),("TCC","高并发复杂","成本高","慎用")],
        runbook_title="事务失效/连接打满/配置漂移",
        runbook_html="<ol><li>查是否走代理/异常类型。</li><li>连接池与长事务。</li><li>配置与端点暴露审计。</li></ol>",
        fail_html="<ul><li>自调用事务。</li><li>事务包HTTP。</li><li>敏感端点裸奔。</li></ul>",
        today_html="<ul><li>支付短事务+Outbox；自调用用例；端点鉴权。</li></ul>",
        conf_title="生产基线",
        conf_code="hikari.maximum-pool-size=与DB对齐\n事务超时；只读事务标注\nmanagement.endpoints 鉴权收敛",
        qas=[
            ("【事务】为何自调用失效？",["同类方法不经代理，切面不生效。","支付。","怪DB。","拆Bean或注入自身代理。","「事务认代理。」"],"fm-spring-q1"),
            ("【边界】事务能包HTTP吗？",["不能；拉长锁与连接。","渠道。","图省事。","先落库再异步。","「事务要短。」"],"fm-spring-q2"),
            ("【Boot】生产最怕啥？",["错误自动配置与端点裸奔。","上线。","本地能跑就行。","配置审计+鉴权。","「配置也是代码。」"],"fm-spring-q3"),
        ],
        koujue_txt="Spring口诀：事务认代理，事务要短，Outbox解耦，端点要收敛。",
        rid="fm-spring-r1",
    )


def spark():
    return gated_entry(
        "ency-fm-spark", "ENCY-FM · Spark全貌", "ENCY-FM-SPARK",
        "Spark 全貌：DF·Shuffle·倾斜·调优·对账·金融/电商/物流",
        ["spark", "shuffle", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>DF/SQL走Catalyst；慢几乎都在Shuffle与倾斜；对账作业必须幂等覆盖写。",
        spine_pos="日终对账/批处理。", serves="批对账", back="ENCY-BD-SPARK → FULLMAP",
        caps=[("DF/SQL","Catalyst/Tungsten","表达"),("Shuffle","宽依赖","慢作业"),("倾斜","热点key","大促批"),
              ("调优","AQE/广播/格式","成本"),("对账","幂等分区替换","正确性"),("场景","金融/电商/物流","选型")],
        mmds=[
            ("diag-fm-spark-shuffle","flowchart LR\n  Map-->Shuffle[(磁盘/网络)]-->Reduce\n  Skew[倾斜key]-->Hot[单任务打满]\n"),
            ("diag-fm-spark-recon","flowchart TD\n  Src[(明细)]-->Job[对账Job]-->Out[(结果分区覆盖写)]\n  Job-->Idem[可重跑]\n"),
        ],
        sources=[
            ("执行计划","DataFrame QueryExecution / Catalyst","df.explain(true) 看物理计划与Exchange(Shuffle)\n"),
            ("倾斜处理伪代码","加盐/两阶段聚合","key' = key + salt\nagg partial → remove salt → final agg\n"),
        ],
        floors=[("宽依赖成本","Shuffle落盘网络；倾斜使单任务成为瓶颈。","Stage UI；Exchange。","盲扩executor。","Shuffle读写量、倾斜任务时长。")],
        chain_html=CHAINS["spark"],
        cases=[
            {"id":"ency-fm-spark-case-cmb","company":"招行类清结算（案例归纳）","scene":"日终对账",
             "land":"DF/SQL；分区覆盖写；可重跑。","pit":"追加写导致双份结果。",
             "fix":"①覆盖写 ②校验和 ③失败重跑。",
             "effect":"公开分享量级/示意区间：对账可重跑且结果稳定（示意）。"},
            {"id":"ency-fm-spark-case-ali","company":"阿里系（案例归纳）","scene":"订单宽表批",
             "land":"AQE；广播小维表；Parquet。","pit":"大表join无计划。",
             "fix":"①explain ②广播阈值 ③倾斜治理。",
             "effect":"公开分享量级/示意区间：作业时长数量级优化常见于治Shuffle后（示意）。"},
            {"id":"ency-fm-spark-case-pdd","company":"拼多多类（案例归纳）","scene":"爆店倾斜",
             "land":"加盐两阶段。","pit":"单reduce打满。",
             "fix":"①发现倾斜key ②加盐 ③单独链路。",
             "effect":"公开分享量级/示意区间：长尾任务时长下降（示意）。"},
            {"id":"ency-fm-spark-case-sf","company":"顺丰类（案例归纳）","scene":"运单日批",
             "land":"按日分区；幂等重跑。","pit":"驱动收集巨大结果OOM。",
             "fix":"①禁止collect大结果 ②写仓。",
             "effect":"公开分享量级/示意区间：驱动稳定（示意）。"},
        ],
        trade_title="Spark边界",
        trade_rows=[("批对账","适合","Flink微批可","—"),("实时亚秒","弱","Flink","—"),("账本事务","不替代OLTP","MySQL","—")],
        runbook_title="慢作业/倾斜/驱动OOM",
        runbook_html="<ol><li>UI找Shuffle Stage。</li><li>查倾斜key。</li><li>禁驱动收齐巨结果。</li><li>重跑幂等。</li></ol>",
        fail_html="<ul><li>追加双份对账。</li><li>盲扩机器。</li><li>collect巨集。</li></ul>",
        today_html="<ul><li>对账覆盖写；explain看Exchange；倾斜加盐。</li></ul>",
        conf_title="意识配置",
        conf_code="spark.sql.adaptive.enabled=true\nbroadcast join threshold按数据\ndriver不收齐巨大结果",
        qas=[
            ("【Shuffle】为何慢？",["宽依赖落盘网络。","调优。","只加机器。","看UI Exchange。","「先看Shuffle。」"],"fm-spark-q1"),
            ("【倾斜】怎么办？",["加盐/两阶段/拆热点。","批。","盲扩。","治倾斜。","「热点拆开。」"],"fm-spark-q2"),
            ("【幂等】重跑？",["分区覆盖写/替换。","对账。","追加。","幂等表。","「重跑可安全。」"],"fm-spark-q3"),
        ],
        koujue_txt="Spark口诀：DF优先，盯Shuffle，治倾斜，对账可重跑。",
        rid="fm-spark-r1",
    )


def flink():
    return gated_entry(
        "ency-fm-flink", "ENCY-FM · Flink全貌", "ENCY-FM-FLINK",
        "Flink 全貌：Checkpoint·水位线·反压·Sink幂等·订单实时·金融/电商/物流",
        ["flink", "checkpoint", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>有状态流计算。Checkpoint是拍照续跑；端到端exactly-once靠CK+幂等/事务Sink；事件时间治乱序。",
        spine_pos="实时支付成功率/风控特征。", serves="实时数仓", back="ENCY-BD-FLINK → FULLMAP",
        caps=[("运行时","JM/TM/算子链","拓扑"),("状态","KeyedState/后端","窗口"),("容错","Checkpoint/Savepoint","恢复"),
              ("时间","事件时间/Watermark","乱序"),("连接","Kafka source/sink","入出"),("反压","CK超时治理","值班"),("场景","金融/电商/物流","选型")],
        mmds=[
            ("diag-fm-flink-ck","flowchart LR\n  Src-->Op[算子状态]\n  Op-->CK[Checkpoint]-->Backend[(StateBackend)]\n  Op-->Sink\n"),
            ("diag-fm-flink-order","sequenceDiagram\n  participant K as Kafka\n  participant F as Flink\n  participant M as 大盘\n  K->>F: OrderPaid\n  F->>F: 事件时间窗口\n  F->>M: upsert指标\n"),
        ],
        sources=[
            ("Checkpoint协调","CheckpointCoordinator 注入barrier","align barriers → snapshot state → confirm\nsink exactly-once: transactional/idempotent writer\n"),
            ("水位线","WatermarkStrategy","eventTime + outOfOrderness\nlate → sideOutput 监控\n"),
        ],
        floors=[("端到端语义","CK保Flink内；外系统要幂等或两阶段。","Kafka事务sink；upsert。","恢复重复写双计。","CK duration、反压、sink重复。")],
        chain_html=CHAINS["flink"],
        cases=[
            {"id":"ency-fm-flink-case-ali","company":"阿里实时数仓（案例归纳）","scene":"支付大盘",
             "land":"Kafka→Flink→upsert指标。","pit":"反压致CK超时。",
             "fix":"①扩并行 ②降状态 ③隔离慢算子。",
             "effect":"公开分享量级/示意区间：CK稳定后大盘可连续（示意）。"},
            {"id":"ency-fm-flink-case-mt","company":"美团/饿了么（案例归纳）","scene":"配送实时",
             "land":"事件时间水位线。","pit":"处理时间窗口乱序错账。",
             "fix":"①事件时间 ②允许延迟 ③侧输出。",
             "effect":"公开分享量级/示意区间：乱序指标偏差收敛（示意）。"},
            {"id":"ency-fm-flink-case-cmb","company":"招行类风控特征（案例归纳）","scene":"流水特征实时",
             "land":"CK+幂等sink；状态TTL。","pit":"状态无限涨。",
             "fix":"①TTL ②状态大小监控。",
             "effect":"公开分享量级/示意区间：状态可控（示意）。"},
            {"id":"ency-fm-flink-case-sf","company":"物流轨迹（案例归纳）","scene":"轨迹实时入搜",
             "land":"至少一次+upsert；可放松EOS。","pit":"强EOS拖吞吐。",
             "fix":"①语义分级 ②主键幂等。",
             "effect":"公开分享量级/示意区间：吞吐与正确性折中达标（示意）。"},
        ],
        trade_title="Flink边界",
        trade_rows=[("实时指标","适合","Spark微批可","—"),("账本事务","不替代OLTP","MySQL","—")],
        runbook_title="CK失败/反压/状态膨胀",
        runbook_html="<ol><li>看反压链路。</li><li>增大间隔或隔离。</li><li>sink幂等校验。</li><li>状态TTL。</li></ol>",
        fail_html="<ul><li>状态无限增长。</li><li>处理时间窗口。</li><li>无幂等sink。</li></ul>",
        today_html="<ul><li>大盘upsert；事件时间水位线；CK与反压进看板。</li></ul>",
        conf_title="意识配置",
        conf_code="checkpoint interval与超时\nstate.backend按规模\nwatermark策略与侧输出",
        qas=[
            ("【CK】恢复重复写？",["sink幂等/事务；CK只保引擎内。","实时。","只加并行。","幂等键。","「恰好一次靠两端。」"],"fm-flink-q1"),
            ("【时间】为何事件时间？",["业务乱序要用事件时钟。","配送。","处理时间偷懒。","水位线。","「业务时钟说话。」"],"fm-flink-q2"),
            ("【反压】怎么判？",["监控反压方向与CK时长。","值班。","只加内存。","剖算子。","「反压有方向。」"],"fm-flink-q3"),
        ],
        koujue_txt="Flink口诀：事件时间，Checkpoint，Sink幂等，反压要剖。",
        rid="fm-flink-r1",
    )


def build():
    return "\n".join([jvm(), juc(), spring(), spark(), flink()])
