# -*- coding: utf-8 -*-
"""FULLMAP HARD GATE · Redis/MySQL/PolarDB(+X)/Gauss/达梦/TDSQL — batch deep rewrite"""
from ency_fullbar import gated_entry
from hardgate_bodies.chains import CHAINS


def _cases(*items):
    return list(items)


def redis():
    return gated_entry(
        "ency-fm-redis", "ENCY-FM · Redis全貌", "ENCY-FM-REDIS",
        "Redis 全貌：结构·过期淘汰·持久化·哨兵集群·缓存锁限流·金融/电商/物流",
        ["redis", "cluster", "persistence", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>单线程命令执行+IO 多路复用；结构与编码定内存；复制异步；预占可以、账本不行。",
        spine_pos="秒杀预占、会话、热点、限流。", serves="库存预占/风控频控", back="T-Found-Redis → FULLMAP",
        caps=[
            ("结构全谱", "十大结构与编码切换", "业务选型"),
            ("过期淘汰", "惰性/抽样、maxmemory-policy", "预占 TTL"),
            ("持久化", "RDB/AOF/混合与 RPO", "重启"),
            ("高可用", "主从、哨兵、Cluster 槽", "故障"),
            ("缓存模式", "Aside/双删/逻辑过期", "商品价"),
            ("锁限流预占", "NX+Lua、令牌/滑动窗口、DECR", "秒杀"),
            ("运维", "大Key/热Key/slowlog", "大促"),
            ("场景差异", "金融/电商/物流边界", "选型"),
        ],
        mmds=[
            ("diag-fm-redis-arch", "flowchart TB\n  App-->Redis\n  Redis-->Cmd[processCommand]\n  Redis-->Rep[主从/Cluster]\n  Redis-->Pers[(AOF/RDB)]\n  App-->Pat[Cache-Aside/预占]\n"),
            ("diag-fm-redis-stock", "flowchart TD\n  Ord[下单]-->Lua[DECR/Lua]\n  Lua -->|ok| Pay[待支付+TTL]\n  Lua -->|fail| Reject\n  Pay-->DB[支付确认落DB]\n  Pay-->Comp[TTL释放/对账补偿]\n"),
        ],
        sources=[
            ("命令执行路径", "server.c processCommand → call → t_*.c",
             "aeProcessEvents → readQuery → processCommand\ndecr → getLongLongFromObject → set\n"),
            ("锁原子删除", "SET key token NX EX + Lua 校验 DEL",
             "SET lock:oid token NX EX 30\nif redis.call('get',KEYS[1])==ARGV[1] then return redis.call('del',KEYS[1]) else return 0 end\n"),
            ("预占边界", "Redis 预占 + DB 条件更新权威",
             "if redis.decr(stock)>0: pendingOrder()\nelse: reject\n-- 支付成功以 DB 为准；Redis 仅加速\n"),
        ],
        floors=[("事件循环与过期", "单线程执行；惰性+activeExpire；打满走淘汰。", "expire.c；evict.c。", "淘汰预占→假可卖；大Key阻塞。", "evicted/expired/ops/slowlog。")],
        chain_html=CHAINS["redis"],
        cases=_cases(
            {"id":"ency-fm-redis-case-pdd","company":"拼多多类秒杀（案例归纳）","scene":"预占库存",
             "land":"Lua/DECR+TTL；支付落 DB；热Key分桶；对账补偿。","pit":"Redis当唯一账本无补偿→超卖/少卖。",
             "fix":"①预占可丢要补 ②DB权威 ③热Key分桶 ④压测淘汰。",
             "effect":"公开分享量级/示意区间：大促预占QPS可为平峰数倍～一个数量级；对账差异分钟～小时级收敛（示意）。"},
            {"id":"ency-fm-redis-case-mt","company":"美团/饿了么类（案例归纳）","scene":"频控与热点商家",
             "land":"滑动窗口限流；本地+Redis二级。","pit":"大Key商家画像阻塞。",
             "fix":"①拆Key ②slowlog ③隔离热点。",
             "effect":"公开分享量级/示意区间：午高峰QPS可为平峰数倍（示意）；慢查治理后P99回落。"},
            {"id":"ency-fm-redis-case-cmb","company":"招行类金融旁路（案例归纳）","scene":"会话/验证码/限流",
             "land":"短TTL；账务不进Redis；切主演练。","pit":"用Redis存余额当权威。",
             "fix":"①职责清单 ②账本只在DB ③演练切主。",
             "effect":"公开分享量级/示意区间：旁路可丢可重建；账务RPO由DB承担（示意）。"},
            {"id":"ency-fm-redis-case-sf","company":"顺丰类物流（案例归纳）","scene":"运单热点查询缓存",
             "land":"运单号Key；短TTL；回源DB。","pit":"超大轨迹List单Key。",
             "fix":"①拆段 ②限长 ③旁路可挂。",
             "effect":"公开分享量级/示意区间：查询命中率常见明显提升（示意非精确）。"},
        ),
        trade_title="Redis 职责边界",
        trade_rows=[("预占/限流/会话","适合","—","—"),("账本余额","禁止唯一真相","MySQL/分布式库","—"),("搜索","弱","ES","—")],
        runbook_title="热Key/大Key/内存打满/切主",
        runbook_html="<ol><li>热/大Key扫描并拆分。</li><li>TTL与淘汰对齐；预占必补偿。</li><li>迁移期重试幂等。</li><li>slowlog进值班。</li></ol>",
        fail_html="<ul><li>无TTL泄漏。</li><li>阻塞大Key。</li><li>Redis当账本。</li><li>锁无token误删。</li></ul>",
        today_html="<ul><li>预占Lua+对账；锁token+Lua删；写进设计评审。</li></ul>",
        conf_title="生产配置基线",
        conf_code="maxmemory-policy=volatile-lru\n预占键必须TTL；appendonly按RPO\nCluster重试+幂等；禁无界大Key",
        qas=[
            ("【结构】ZSet底层？",["跳表+字典：排序O(logN)，点查O(1)。","排行榜。","只背用途。","讲编码切换。","「跳表管顺序，哈希管点查。」"],"fm-redis-q1"),
            ("【场景】预占被淘汰？",["允许丢，对账补偿，DB权威。","秒杀。","开AOF就万事大吉。","TTL+补偿任务。","「预占可丢要补。」"],"fm-redis-q2"),
            ("【锁】防误删？",["token+Lua校验；看门狗续期。","跨机互斥。","裸DEL。","公共锁组件。","「锁要认主人。」"],"fm-redis-q3"),
        ],
        koujue_txt="Redis 口诀：结构选对，预占可丢，账本在库，热键要拆，锁认主人。",
        rid="fm-redis-r1",
    )


def mysql():
    return gated_entry(
        "ency-fm-mysql", "ENCY-FM · MySQL全貌", "ENCY-FM-MYSQL",
        "MySQL/InnoDB 全貌：隔离·锁·索引·redo/binlog·复制HA·分片边界·金融/电商/物流",
        ["mysql", "innodb", "mvcc", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>InnoDB=聚簇索引账本+MVCC+redo/undo+binlog。订单幂等=唯一键+条件更新；付后读主。",
        spine_pos="订单/支付/售后账本。", serves="正逆向事务", back="T-Found-MySQL → FULLMAP",
        caps=[
            ("存储","表空间/页/聚簇索引","点查"),("事务","ACID/隔离/MVCC","支付"),("锁","行/间隙/死锁","并发退"),
            ("日志","redo/undo/binlog组提交","恢复复制"),("复制HA","半同步/切换演练","RPO/RTO"),
            ("扩展","读写分离/分片边界","增长"),("运维","慢查/长事务/池","值班"),("场景差异","金融/电商/物流","选型"),
        ],
        mmds=[
            ("diag-fm-mysql-tx","flowchart TD\n  SQL-->Opt[优化器]-->InnoDB\n  InnoDB-->Redo[(redo)]\n  InnoDB-->Undo[(undo)]\n  InnoDB-->Bin[(binlog)]-->Replica\n"),
            ("diag-fm-mysql-pay","sequenceDiagram\n  participant P as 支付回调\n  participant D as MySQL\n  P->>D: INSERT幂等键\n  P->>D: UPDATE WHERE status=CREATED\n  alt row=1\n    D-->>P: 推进态机\n  else row=0\n    D-->>P: 查现态幂等\n  end\n"),
        ],
        sources=[
            ("条件更新幂等","handler::ha_update_row / lock_rec","UPDATE orders SET status='PAID' WHERE id=? AND status='CREATED';\n-- row_count=0 → 查现态\n"),
            ("提交秩序","InnoDB prepare → binlog → commit","crash-safe：redo与binlog协调；复制看GTID\n"),
            ("间隙锁","lock0lock 当前读","-- RR范围可能gap；收紧条件，短事务\n"),
        ],
        floors=[("MVCC+锁","快照读ReadView；当前读加锁。","lock0*/read0*/trx0*（认知）。","FOR UPDATE锁扩大；长事务包HTTP。","data_locks/死锁/EXPLAIN/innodb_trx。")],
        chain_html=CHAINS["mysql"],
        cases=_cases(
            {"id":"ency-fm-mysql-case-ali","company":"阿里系订单库（案例归纳）","scene":"支付回调幂等",
             "land":"唯一键+条件更新；短事务；先落库再异步。","pit":"长事务包HTTP→锁等待雪崩。",
             "fix":"①回调只本地短事务 ②外部异步 ③定锁序。",
             "effect":"公开分享量级/示意区间：回调重复常见；幂等后资损工单显著下降（示意）。"},
            {"id":"ency-fm-mysql-case-cmb","company":"招行类账务（案例归纳）","scene":"流水+余额",
             "land":"先流水后余额条件更新；热户治理；半同步取向。","pit":"先改余额后写流水→账实不符。",
             "fix":"①顺序强制 ②对账三针 ③热户拆分。",
             "effect":"公开分享量级/示意区间：对账闭环率接近100%为工程目标（示意）。"},
            {"id":"ency-fm-mysql-case-sf","company":"顺丰类物流（案例归纳）","scene":"运单状态机",
             "land":"运单号主键；条件更新；轨迹旁路。","pit":"深分页拖垮。",
             "fix":"①寻求法 ②归档 ③轨迹不进主事务。",
             "effect":"公开分享量级/示意区间：日运单十万～百万级（视体量示意）。"},
            {"id":"ency-fm-mysql-case-pdd","company":"拼多多类电商（案例归纳）","scene":"大促订单写",
             "land":"核心/营销隔离；短事务；读写分离。","pit":"一套库扛报表扫描。",
             "fix":"①读写分离 ②报表下沉 ③池分级。",
             "effect":"公开分享量级/示意区间：大促写QPS可为平峰数倍～一个数量级（示意）。"},
        ),
        trade_title="MySQL vs 分布式库 vs 缓存",
        trade_rows=[("单分片事务","最清晰","看产品","无"),("写扩展","垂直/分片","TDSQL/OB/PolarDB-X","不承担"),("账本权威","是","是(单片)","否")],
        runbook_title="死锁/慢查/延迟/长事务",
        runbook_html="<ol><li>死锁日志定锁序。</li><li>EXPLAIN+慢日志。</li><li>付后读主。</li><li>杀长事务。</li></ol>",
        fail_html="<ul><li>无唯一键双付。</li><li>深分页。</li><li>float金额。</li></ul>",
        today_html="<ul><li>唯一键+条件更新；禁float；付后读主进规范。</li></ul>",
        conf_title="生产配置意识项",
        conf_code="transaction_isolation=READ-COMMITTED #按业务\nbinlog_format=ROW\nsync_binlog/innodb_flush_log_at_trx_commit 按RPO",
        qas=[
            ("【锁】间隙锁何时？",["RR范围/非唯一当前读可能gap。","售后。","怪并发。","收紧条件/评估RC。","「范围即间隙。」"],"fm-mysql-q1"),
            ("【幂等】回调两次？",["唯一键冲突当成功；条件更新看row_count。","支付。","再扣一次。","幂等表+态机。","「冲突即成功。」"],"fm-mysql-q2"),
            ("【分片】何时不上？",["归档/RO/垂直拆未证明不够。","评审。","提前炫技。","量化再手术。","「分片是手术。」"],"fm-mysql-q3"),
        ],
        koujue_txt="MySQL 口诀：唯一键幂等，条件更新，短事务，付后读主，分片是手术。",
        rid="fm-mysql-r1",
    )


def polardb():
    return gated_entry(
        "ency-fm-polardb", "ENCY-FM · PolarDB/PolarDB-X全貌", "ENCY-FM-POLARDB",
        "PolarDB/PolarDB-X 全貌：共享存储·RO·CN·DN·GMS·CDC·边界·金融/电商/物流",
        ["polardb", "polardb-x", "cn", "dn", "gms", "cdc", "shared-storage", "fullmap", "hardgate"],
        plain_txt="<b>开篇钉产品：</b>PolarDB=共享存储一写多读；PolarDB-X=CN/DN/GMS 分布式。先治读，写顶了再上X；CDC旁路，资损用Outbox。",
        spine_pos="订单库读扩展与分布式写扩展。", serves="OLTP读写扩展", back="ENCY-D-POLARDB → FULLMAP",
        caps=[
            ("共享存储PolarDB","计算存储分离、Primary/RO","读扩展"),
            ("延迟路由","RO lag、付后读主、sticky","支付回跳"),
            ("CN","解析优化调度、无状态入口","连接扩展"),
            ("DN","分片存储、本地事务","写扩展"),
            ("GMS","元数据、拓扑、DDL","控制面"),
            ("协作","CN×DN×GMS全链路","排障"),
            ("CDC","DTS/Canal、乱序重复DDL","搜推数仓"),
            ("边界","单主写vs分片、Outbox","选型"),
        ],
        mmds=[
            ("diag-fm-polar-shared","flowchart LR\n  W[写]-->Primary\n  R[读]-->RO\n  Primary-->Stor[(共享存储多副本)]\n  RO-->Stor\n  Pay[付后读己之写]-->Primary\n"),
            ("diag-fm-polar-x-collab","flowchart TB\n  Client-->CN[CN解析优化调度]\n  CN-->GMS[GMS元数据拓扑]\n  CN-->DN1[(DN分片1)]\n  CN-->DN2[(DN分片2)]\n  GMS-.->|schema/topology|CN\n  GMS-.->|DDL|DN1\n  GMS-.->|DDL|DN2\n"),
            ("diag-fm-polar-cdc","flowchart LR\n  DB[(PolarDB/X)]-->Log[binlog/DN日志]\n  Log-->CDC[DTS/Canal类]\n  CDC-->MQ[MQ/Kafka]\n  MQ-->OMS[履约]\n  MQ-->Search[搜推]\n  MQ-->DW[数仓]\n  Outbox[核心Outbox]-.->|资损优先|MQ\n"),
        ],
        sources=[
            ("共享存储路由","双数据源 Primary vs RO","if needReadYourWrites or inTx: primary()\nelif roLag<SLA: ro()\nelse: primary()\n"),
            ("CN分布式计划","Parser→Optimizer→Scheduler→Gather","plan=optimize(sql, metaFromGMS)\nfutures=[dn.exec(f) for f in plan.scatter]\nreturn merge(futures)\n"),
            ("GMS版本闸","schema_version/topology发布","DDL: lock_meta→version++→DN→CN invalidate\n# 错片先对GMS与CN缓存版本\n"),
            ("CDC幂等","位点+下游幂等键","key=(gtid|file:pos,table,pk)\nif seen(key): return\nupsert(); # DDL pause→migrate→resume\n"),
        ],
        floors=[("两产品两套底板","共享存储=一份盘多计算；X=CN算+DN存+GMS控。","云存储多副本；CN/DN/GMS；CDC管道。","付后读RO；跨片当单片；GMS脏缓存；CDC当Outbox。","RO lag/跨片比/GMS健康/CDC位点/DN热点。")],
        chain_html=CHAINS["polardb"],
        cases=_cases(
            {"id":"ency-fm-polar-case-ali","company":"阿里云消费零售（案例归纳）","scene":"订单读扩展+支付回跳",
             "land":"写Primary；报表RO；付后sticky主库。","pit":"回跳读RO→态不一致客诉。",
             "fix":"①关键读强制主 ②lag阈值 ③压测回跳。",
             "effect":"公开分享量级/示意区间：读流量常可分走较大比例到RO（示意）；「已付仍待支付」客诉下降。"},
            {"id":"ency-fm-polar-case-cmb","company":"招行类金融（案例归纳）","scene":"核心库上云评估",
             "land":"优先共享存储兼容；强同步/演练；分布式慎入。","pit":"未分清X与共享存储就上分片。",
             "fix":"①产品边界评审 ②兼容套件 ③切换演练 ④对账。",
             "effect":"公开分享量级/示意区间：以RPO/RTO与对账闭环为门禁（示意）。"},
            {"id":"ency-fm-polar-case-pdd","company":"拼多多类电商（案例归纳）","scene":"单主写顶上PolarDB-X",
             "land":"分片键用户/订单；CN扩连接；热点隔离；严控跨片。","pit":"加RO指望写扩展；爆店热点片。",
             "fix":"①键评审 ②加盐/隔离 ③跨片预算 ④CDC与Outbox分工。",
             "effect":"公开分享量级/示意区间：写随DN水平扩展；大促需热点专项（示意）。"},
            {"id":"ency-fm-polar-case-sf","company":"顺丰类物流（案例归纳）","scene":"运单库+轨迹CDC",
             "land":"核心态库；轨迹CDC→Kafka→检索。","pit":"CDC乱序轨迹回退。",
             "fix":"①序号upsert ②DDL窗口 ③位点告警。",
             "effect":"公开分享量级/示意区间：轨迹事件十万～百万级/日（示意）；lag分钟级响应。"},
        ),
        trade_title="PolarDB vs PolarDB-X vs 中间件分片",
        trade_rows=[("读扩展","强(RO)","强","中"),("写扩展","弱(单主)","强","中自建"),("事务","清晰","单片易跨片贵","跨片贵"),("控制面","存储/计算托管","GMS关键","自建")],
        runbook_title="RO延迟/切主/GMS/热点DN/CDC",
        runbook_html="<ol><li>RO lag→读主/sticky。</li><li>切主核对连接与位点。</li><li>错片→GMS版本与CN缓存。</li><li>热点DN→限流/加盐。</li><li>CDC延迟/DDL→暂停修schema。</li></ol>",
        fail_html="<ul><li>两产品混谈。</li><li>付后读RO。</li><li>用RO解决写瓶颈。</li><li>CDC替代Outbox做资损。</li></ul>",
        today_html="<ul><li>画清PolarDB vs X与CN/DN/GMS；付后读主扫描；CDC/Outbox职责表进仓。</li></ul>",
        conf_title="生产配置/路由规范",
        conf_code="transactional_ds=primary\nreporting_ds=readonly\nread_your_writes=sticky_primary\nro_lag_threshold_ms=...\n# X: monitor cross_shard_ratio,gms_health,dn_cpu,cdc_checkpoint",
        qas=[
            ("【产品】PolarDB与X差异？",["共享存储一写多读 vs CN/DN/GMS分片。","选型。","混成一词。","画两张拓扑。","「一份盘 vs 切开算存控。」"],"fm-polar-q1"),
            ("【CN/DN/GMS】职责？",["CN解析调度无状态；DN存片本地事务；GMS元数据拓扑DDL。","PolarDB-X。","只记得分片。","按请求路径口述。","「算-存-控三面。」"],"fm-polar-q2"),
            ("【CDC】vs Outbox？",["资损核心Outbox；CDC旁路搜推数仓；都要幂等与DDL门禁。","履约/搜推。","只开DTS。","职责表+位点监控。","「核心出箱，旁路CDC。」"],"fm-polar-q3"),
        ],
        koujue_txt="Polar口诀：共享存储治读，X靠CN/DN/GMS，付后读主，CDC旁路，跨片当事故。",
        rid="fm-polar-r1",
    )


def gauss():
    return gated_entry(
        "ency-fm-gauss", "ENCY-FM · GaussDB全貌", "ENCY-FM-GAUSS",
        "GaussDB 全貌：拓扑·一致性·兼容·迁移·备份演练·金融/电商/物流",
        ["gaussdb", "xinchuang", "fullmap", "hardgate"],
        plain_txt="<b>开篇即门禁：</b>先认集中式/分布式拓扑与事务模型，再迁流量；方言/隔离静默差是最大坑。",
        spine_pos="信创订单/报备库。", serves="合规OLTP", back="ENCY-D-GAUSS → FULLMAP",
        caps=[("形态拓扑","集中vs分布角色","评审"),("一致性","副本/提交/脑裂","账务"),("隔离","与MySQL假设差","用例"),
              ("兼容","SQL/驱动/ORM","迁移"),("迁移","双跑灰度","切流"),("运维","备份演练","RTO"),("边界","跨片/生态","模型"),("场景","金融强制","选型")],
        mmds=[
            ("diag-fm-gauss-topo","flowchart TB\n  App-->Entry[接入/协调]\n  Entry-->DN[(数据节点主备)]\n  Doc[先确认真实拓扑]-->Entry\n"),
            ("diag-fm-gauss-mig","flowchart TD\n  A[兼容+拓扑]-->B[迁移]-->C[双跑]-->D[灰度]-->E[演练签字]\n"),
        ],
        sources=[
            ("迁移校验","JDBC/方言/核心SQL回归","for sql in critical_suite:\n  assert same_result(legacy,gauss)\nassert isolation_cases()\n"),
            ("拓扑门禁","架构评审伪代码","require(topology_doc and failover_drill)\nif distributed: require(shard_key_design)\n"),
        ],
        floors=[("拓扑决定事务","集中式≈主备；分布式问分片与跨片。","厂商文档副本/隔离。","方言100%假设→算错。","兼容失败用例、切换RTO、对账差。")],
        chain_html=CHAINS["gauss"],
        cases=_cases(
            {"id":"ency-fm-gauss-case-cmb","company":"招行类信创（案例归纳）","scene":"核心交易评估",
             "land":"拓扑确认+兼容套件+回调压测+演练。","pit":"未测隔离差异。",
             "fix":"①钉拓扑 ②隔离用例 ③双跑 ④演练签字。",
             "effect":"公开分享量级/示意区间：用例全绿与演练RTO达标为门禁（示意）。"},
            {"id":"ency-fm-gauss-case-yy","company":"用友类政企（案例归纳）","scene":"单据库迁移",
             "land":"双跑对账；备份恢复。","pit":"只迁数据不演练。",
             "fix":"①定期恢复 ②抽样对账 ③回滚预案。",
             "effect":"公开分享量级/示意区间：双跑差异收敛到可解释集合（示意）。"},
            {"id":"ency-fm-gauss-case-gov","company":"政务/国企仓配（案例归纳）","scene":"库存单据信创",
             "land":"集中式优先；报表分离。","pit":"分布式当银弹。",
             "fix":"①能集中不分布 ②跨片禁入核心。",
             "effect":"公开分享量级/示意区间：稳定与合规优先于极致吞吐（示意）。"},
            {"id":"ency-fm-gauss-case-ecom","company":"电商中台政策驱动（案例归纳）","scene":"非核心库先迁",
             "land":"营销/配置先行；核心后置。","pit":"核心边缘一起切。",
             "fix":"①分级迁移 ②核心加倍套件。",
             "effect":"公开分享量级/示意区间：分波次降低一次性风险（示意）。"},
        ),
        trade_title="Gauss选型对照",
        trade_rows=[("信创强制","高","达梦同池","MySQL云"),("生态","要培训","要培训","熟"),("分布式","看版型","弱于专用分片","另案")],
        runbook_title="切换/兼容回归/恢复演练",
        runbook_html="<ol><li>切换检查表。</li><li>核心SQL红线全绿。</li><li>恢复演练签字。</li><li>回滚开关。</li></ol>",
        fail_html="<ul><li>未认拓扑。</li><li>只迁数据不测隔离。</li><li>无演练谈RTO。</li></ul>",
        today_html="<ul><li>拓扑确认会；差异表+用例进仓。</li></ul>",
        conf_title="迁移门禁",
        conf_code="topology_doc=signed\ncritical_sql_suite=green\nbackup_restore_drill=ok\nrollback_switch=ready",
        qas=[
            ("【第一步】最该问啥？",["拓扑/副本/隔离/RPO/RTO/是否分片。","选型。","只比报价。","签字清单。","「先问拓扑。」"],"fm-gauss-q1"),
            ("【风险】最大静默坑？",["方言与隔离差异。","迁移。","只校验行数。","语义用例锁命。","「用例锁命。」"],"fm-gauss-q2"),
            ("【演练】为何杀节点？",["文档RTO≠真实。","运维。","有备份文件即可。","定期演练签字。","「不演练=没备份。」"],"fm-gauss-q3"),
        ],
        koujue_txt="Gauss口诀：先认拓扑，用例锁命，双跑对账，演练才算数。",
        rid="fm-gauss-r1",
    )


def dm():
    return gated_entry(
        "ency-fm-dm", "ENCY-FM · 达梦全貌", "ENCY-FM-DM",
        "达梦全貌：Oracle替换·引擎事务·守护切换·备份演练·边界·金融/电商/物流",
        ["dameng", "xinchuang", "fullmap", "hardgate"],
        plain_txt="<b>开篇即路径：</b>达梦≈Oracle国产方向盘——习惯近，分页/空串/序列/工具链必须重测；备份不演练=零。",
        spine_pos="信创交易/报备。", serves="合规OLTP", back="ENCY-D-DM → FULLMAP",
        caps=[("替换路径","Oracle差异清单","改造"),("引擎事务","集中式账本/权限","账本"),("高可用","守护/集群","RTO"),
              ("备份","校验+演练","RPO"),("应用适配","分页/空串/序列","列表正确"),("运维","监控对接","值班"),("边界","生态人才","编制"),("场景","政企金融","选型")],
        mmds=[
            ("diag-fm-dm-mig","flowchart LR\n  Ora[(Oracle)]-->Diff[差异表Git]-->App[改SQL/ORM]-->Dual[双跑]-->DM[(达梦)]\n"),
            ("diag-fm-dm-bak","flowchart TD\n  Bak[备份]-->Chk[校验]-->Drill[旁路恢复]-->Smoke[冒烟]-->Sign[签字]\n"),
        ],
        sources=[
            ("方言适配","DAO/ORM分页与空串","-- rownum vs FETCH/LIMIT\n-- '' vs NULL；sequence\nassert page_stable()\n"),
            ("守护切换","Runbook伪代码","precheck lag\nfailover → reconfig pool\nsmoke critical_sql\n"),
        ],
        floors=[("替换不是改驱动","语义差致错页/错账。","JDBC/ORM/备份工具。","售后错页；空串匹配错。","差异表覆盖、演练记录、分页用例。")],
        chain_html=CHAINS["dm"],
        cases=_cases(
            {"id":"ency-fm-dm-case-yy","company":"政企用友生态（案例归纳）","scene":"Oracle→DM单据",
             "land":"差异表+双跑+分页回归。","pit":"空串与NULL语义差。",
             "fix":"①空串用例 ②稳定排序 ③回滚预案。",
             "effect":"公开分享量级/示意区间：双跑差异收敛后切流（示意）。"},
            {"id":"ency-fm-dm-case-fin","company":"金融信创（案例归纳）","scene":"报备/渠道库",
             "land":"守护+定期恢复演练。","pit":"只靠盘阵无应用演练。",
             "fix":"①旁路恢复 ②冒烟 ③签字。",
             "effect":"公开分享量级/示意区间：演练RTO达标为门禁（示意）。"},
            {"id":"ency-fm-dm-case-wms","company":"国企仓配（案例归纳）","scene":"库存单据",
             "land":"集中式；核心SQL套件。","pit":"序列并发假设照搬。",
             "fix":"①序列压测 ②唯一约束兜底。",
             "effect":"公开分享量级/示意区间：零错页/零错号验收（示意）。"},
            {"id":"ency-fm-dm-case-tel","company":"大型企业（案例归纳）","scene":"报表分流",
             "land":"交易与报表分离。","pit":"替换后仍大报扫交易库。",
             "fix":"①只读/数仓 ②审计大SQL。",
             "effect":"公开分享量级/示意区间：交易P99与报表解耦（示意）。"},
        ),
        trade_title="达梦边界对照",
        trade_rows=[("Oracle替换","常见","Gauss同池","—"),("互联网生态","弱于MySQL","MySQL/PolarDB","—")],
        runbook_title="差异回归/切换/备份恢复",
        runbook_html="<ol><li>差异变更必跑分页/空串/序列。</li><li>切换后池终点。</li><li>30天恢复演练签字。</li></ol>",
        fail_html="<ul><li>未改分页。</li><li>无演练谈备份。</li><li>空串未测。</li></ul>",
        today_html="<ul><li>差异表进Git；恢复演练排期。</li></ul>",
        conf_title="门禁",
        conf_code="dialect_diff_sheet=in_repo\npage_null_sequence_suite=green\nrestore_drill_last_30d=ok",
        qas=[
            ("【迁移】先做什么？",["差异清单进仓挂用例。","启动。","直接切驱动。","清单+双跑。","「差异表进仓。」"],"fm-dm-q1"),
            ("【RPO】如何证备份？",["旁路恢复+冒烟签字。","审计。","有文件即可。","30天演练。","「演练才算备份。」"],"fm-dm-q2"),
            ("【应用】分页坑？",["方言差致错页漏行。","列表。","照搬rownum。","适配层+稳定order by。","「分页必回归。」"],"fm-dm-q3"),
        ],
        koujue_txt="达梦口诀：差异表进仓，分页空串必测，备份必演练。",
        rid="fm-dm-r1",
    )


def tdsql():
    return gated_entry(
        "ency-fm-tdsql", "ENCY-FM · TDSQL全貌", "ENCY-FM-TDSQL",
        "TDSQL 全貌：代理路由·分片键·分布式事务·热点·审计·金融/电商/物流",
        ["tdsql", "sharding", "fullmap", "hardgate"],
        plain_txt="<b>开篇即底板：</b>数据切开。代理看分片键；跨片当事故预算；报表禁扫生产。",
        spine_pos="高并发订单水平扩展。", serves="订单写扩展", back="ENCY-D-TDSQL → FULLMAP",
        caps=[("架构","代理/计算+DN+管控","路由"),("分片键","用户/订单/商户","模型"),("事务","单片vs分布式","支付"),
              ("索引","全局二级索引成本","查询"),("热点","倾斜治理","大促"),("治理","扩容/SQL审计","规范"),("旁路","按片日志/数仓","分析"),("场景","金融/电商/物流","选型")],
        mmds=[
            ("diag-fm-tdsql-route","flowchart TD\n  SQL-->Proxy\n  Proxy-->R{分片键?}\n  R -->|有| One[单DN本地事务]\n  R -->|无| Fan[扇出或拒绝]\n"),
            ("diag-fm-tdsql-hot","flowchart LR\n  Hot[热点片]-->Salt[加盐/二级拆]\n  Hot-->Iso[隔离库]\n  Hot-->Limit[限流]\n"),
        ],
        sources=[
            ("路由红线","SQL必须带分片键","SELECT * FROM orders WHERE order_id=?\n-- 禁止无键扫生产\n"),
            ("跨片预算","2PC/XA监控","if plan.cross_shard:\n  metrics.cross_shard_tx++\n  require(budget)\n"),
        ],
        floors=[("跨片成本","扇出与2PC放大延迟失败率；热点片写爆。","代理计划；两阶段；DN锁。","非键扇出；爆店打满一片。","跨片比/慢SQL/DN CPU。")],
        chain_html=CHAINS["tdsql"],
        cases=_cases(
            {"id":"ency-fm-tdsql-case-fin","company":"腾讯云金融/支付类（案例归纳）","scene":"交易分片",
             "land":"用户/商户键；单片事务；报表数仓。","pit":"管理报表无键扫生产。",
             "fix":"①审计拦截 ②数仓出口 ③单片证明。",
             "effect":"公开分享量级/示意区间：跨片比例压到低水位为常见目标（示意）。"},
            {"id":"ency-fm-tdsql-case-ecom","company":"电商大促（案例归纳）","scene":"热点商户",
             "land":"热点隔离+限流+加盐。","pit":"单商户写爆一片。",
             "fix":"①热点发现 ②二级拆 ③限流。",
             "effect":"公开分享量级/示意区间：热点片CPU可顶满；治理后恢复吞吐（示意）。"},
            {"id":"ency-fm-tdsql-case-sf","company":"顺丰类物流（案例归纳）","scene":"运单分片",
             "land":"waybill/用户键；轨迹旁路。","pit":"按时间无键扫。",
             "fix":"①查询对齐键 ②分析走仓。",
             "effect":"公开分享量级/示意区间：点查稳定，分析解耦（示意）。"},
            {"id":"ency-fm-tdsql-case-yy","company":"用友类企业（案例归纳）","scene":"多租户",
             "land":"租户键；慎跨租户join。","pit":"管理端跨租户扇出。",
             "fix":"①租户键强制 ②管理查询隔离。",
             "effect":"公开分享量级/示意区间：故障域按租户收敛（示意）。"},
        ),
        trade_title="TDSQL vs PolarDB vs 中间件分片",
        trade_rows=[("写扩展","强","弱","中自建"),("运维","厂商","云托管","自建重"),("跨片","贵","无","贵")],
        runbook_title="跨片审计/热点/搬迁",
        runbook_html="<ol><li>审计无键SQL与跨片事务。</li><li>热点片限流与拆分。</li><li>搬迁窗口与回滚。</li></ol>",
        fail_html="<ul><li>广播SQL。</li><li>随手跨片事务。</li><li>报表扫生产。</li></ul>",
        today_html="<ul><li>售后查询路径与分片键对齐；跨片预算进监控。</li></ul>",
        conf_title="红线",
        conf_code="require_shard_key=true\ncross_shard_tx_budget=monitored\nhot_shard_alert=on\nreport_to_warehouse=enforced",
        qas=[
            ("【键】怎么选？",["对齐最高频点查；接受列表二次设计。","模型。","随意。","评审键。","「键定终身。」"],"fm-tdsql-q1"),
            ("【热点】怎么办？",["加盐/隔离/限流。","大促。","盲加DN。","先治倾斜。","「先治倾斜。」"],"fm-tdsql-q2"),
            ("【事务】跨片？",["当例外；能避则避。","支付。","随便开。","单片设计。","「跨片当事故。」"],"fm-tdsql-q3"),
        ],
        koujue_txt="TDSQL口诀：分片键定终身，跨片当事故，报表走数仓，热点先治理。",
        rid="fm-tdsql-r1",
    )


def build():
    return "\n".join([redis(), mysql(), polardb(), gauss(), dm(), tdsql()])
